### ISSUE TITLE
Method ToMb() not available in remote Exchange PS session without Exchange Mgmt Tools

### ISSUE THREAD

**Issue by dwhitney7** [alejandr0x0/Find-MailboxDelegates#3]
`Error: Method invocation failed because [Deserialized.Microsoft.Exchange.Data.ByteQuantifiedSize] does not contain a method named 'ToMb'. at 591`

Appears to be just like https://emg.johnshopkins.edu/?p=880, which has some messy conversion code to make it work regardless. There may be a better way to have this consistently with something else in PS?

**Comment by soyalejolopez** [comment]
Thanks David! The issue was due to deserialization on remote sessions. Francesco updated with manual MB conversion versus using the method. Also I've updated to use RemoteExchange vs Remoting which would fix this too.
